---
title: "Data Analysis Case Study"
author: "Simi"
date: "2026-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Analysis Case Study: Changes in Fine Particle Air Pollution in the U.S.



```{r}
unzip("book_datasets.zip")
```

## Reading the 19999 dataset


```{r}
pm0 <- read.table("pm25_data/RD_501_88101_1999-0.txt", comment.char = "#", header = FALSE, sep = "|", na.strings = "")
dim(pm0)
```
## Snapshot of the data
```{r}
head(pm0[,1:13])
```

## attach column headers to the dataset and ensure proper formatting
```{r}
cnames <- readLines("pm25_data/RD_501_88101_1999-0.txt", 1)

cnames <- strsplit(cnames, "|", fixed = TRUE)
```


## Ensures names are properly formatted
```{r}
names(pm0) <- make.names(cnames[[1]])

```


```{r}
head(pm0[, 1:13])

```



```{r}

x0 <- pm0$Sample.Value
summary(x0)
```


```{r}
mean(is.na(x0))

```

## Reading in the 2012 data

```{r}

pm1 <- read.table("pm25_data/RD_501_88101_2012-0.txt", comment.char = "#",
 header = FALSE, sep = "|", na.strings = "", nrow = 1304290)
```

## Set the column headers similar to the 1999 datset

```{r}
names(pm1) <- make.names(cnames[[1]])
x1 <- pm1$Sample.Value

```

## Results
### Entire U.S. Analysis

### Boxplot of monitor values for 1999 and 2012
```{r}

boxplot(log2(x0), log2(x1))

```


```{r}
summary(x0)

```


```{r}
 summary(x1)

```


```{r}
negative <- x1 < 0
mean(negative, na.rm = T)
```

```{r}
#Date formatted as character strings. Use as.date to convert them into date objects

dates<-pm1$Date
dates <- as.Date(as.character(dates), "%Y%m%d")

```


```{r}

```



```{r}

```



```{r}

```



```{r}

```




































































































































































































































































































































































































